############################# Default configuration ########################
baseURL = "https://webplusun.fr/"
title = "Agence web éco-responsable Bayonne"
theme = "agico-hugo"
# post pagination
paginate = "4"
# post excerpt
summaryLength = "10"
# disqus short name
disqusShortname = "agico" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = ["fr"] # desable language from here

################################### Plugins #################################
# CSS Plugins
# [[params.plugins.css]]
# link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/font-awesome/font-awesome.min.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"
[[params.plugins.css]]
link = "plugins/aos/aos.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
#[[params.plugins.js]]
#link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[[params.plugins.js]]
link = "plugins/aos/aos.js"


  
############################ navigation #################################

# main menu    
[[menu.main]]
name = "WebPlusUn"
URL = "webplusun"
weight = 2
  
[[menu.main]]
name = "Services"
URL = "service"
weight = 3

[[menu.main]]
name = "Références"
URL = "references"
weight = 4

[[menu.main]]
name = "Blog"
URL = "blog"
weight = 5

###########################
#Footer menu
[[menu.footer]]
name = "WebPlusUn"
URL = "webplusun"
weight = 1

[[menu.footer]]
name = "Prenons contact"
URL = "contact"
weight = 2

[[menu.footer]]
name = "À quel prix ?"
URL = "tarifs"
weight = 3

[[menu.footer]]
name = "Mentions légales"
URL = "mentions-legales"
weight = 4


########################### Default parameters ###########################
[params]
logo1 = "images/web-plus-un-logo.webp"
logo2 = "images/web-plus-un-logo.png"
# Meta data
description = "WebPlusUn propose un service en conception de site éco-responsable, diagnostic de performances et optimisations SXO pour améliorer l'avenir de votre web."
author = "WebPlusUn"
# contact info
address = "3, Rue Hélène Boucher 40220 TARNOS, France"
mobile = "06.48.48.45.80"
email = "fred.maget@webplusun.fr"
horaires = "Lundi-Vendredi 9:00-18:00"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# Google Analytics
google_analytics_id = "Your ID"

# Preloader
[params.preloader]
enable = true
preloader = "images/web-plus-un-logo.png"

# Navigation button
[params.navigation_button]
enable = true
label = "Ça vous intrigue ?"
link = "contact"

###########################
# Subscription
[params.subscription]
enable = false
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours

# google map
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"

########################### social icon ############################
[[params.social]]
icon = "fa-facebook"
URL = "https://www.facebook.com/WebPlusUn/"


################################### English language #####################################
[Languages.en]
languageName = "En"
languageCode = "fr-fr"
contentDir = "content/pages"
weight = 1
home = "Accueil"
# footer content
footer_content = "Une démarche éco-responsable vous intéresse ? <br>Que ce soit la conception d'un nouveau site, ou le diagnostic de performances d'un site existant, prenons rendez-vous et discutons de votre projet."
# copyright
copyright = "WebPlusUn 2020 tous droits réservés - SCIC Interstices Siret 448 220 830 000 39"


################################### French language #####################################
[Languages.fr]
languageName = "Fr"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 2
home = "Accueil"
# footer content
footer_content = "Lorem ipsum dolor amet consectetur adipisicing elit sed eiusm tempor incididunt ut labore dolore magna aliqua enim ad minim veniam quis nostrud exercitation ullamaboris nisi ut aliquip.exea commodo consequat. Duis aute irure dolor in reprehenderit."
# copyright
copyright = "Copyright &copy; 2020 a hugo theme by [themefisher](https://themefisher.com)"